### ISSUE TITLE
Does it support java Roaring64NavigableMap? 

### ISSUE THREAD

**Issue by zuston** [saulius/croaring-rs#102]
Thanks for your great work!

**Comment by saulius** [comment]
Hello @zuston,

Depends on what you mean by support. You can serialize and deserialize a [Treemap](https://docs.rs/croaring/0.8.1/croaring/treemap/struct.Treemap.html) into `Roaring64NavigableMap`. Check [here](https://github.com/saulius/croaring-rs/blob/01375bb6699f228b6ffa6d6fa3aabd1256cf8b49/croaring/tests/lib.rs#L258-L268) for an example, there are also more examples in that file.

**Comment by zuston** [comment]
> Hello @zuston,
> 
> 
> 
> Depends on what you mean by support. You can serialize and deserialize a [Treemap](https://docs.rs/croaring/0.8.1/croaring/treemap/struct.Treemap.html) into `Roaring64NavigableMap`. Check [here](https://github.com/saulius/croaring-rs/blob/01375bb6699f228b6ffa6d6fa3aabd1256cf8b49/croaring/tests/lib.rs#L258-L268) for an example, there are also more examples in that file.
> 
> 

Oh, thanks for your reply. Let me take a try 😁

**Comment by zuston** [comment]
Thank you very much, I have checked successfully.
