### ISSUE TITLE
Upgrade to CRoaring 0.2.12

### ISSUE THREAD

**Issue by lemire** [saulius/croaring-rs#17]
https://github.com/RoaringBitmap/CRoaring/releases/tag/v0.2.12

Pregenerated unity builds...

https://github.com/lemire/CRoaringUnityBuild

**Comment by lemire** [comment]
With latest CRoaring, we have iterators that could be useful...

```
roaring_uint32_iterator_t *  i = roaring_create_iterator(r1);
while(i->has_value) {
   //use: i->current_value
   roaring_advance_uint32_iterator(i);
}
roaring_free_uint32_iterator(i);
```

**Comment by saulius** [comment]
Upgraded. Good idea with unity builds, @lemire! It would be nice if unity repo had version tags just like the original CRoaring repo, what do you think?

I'll take a look into iterator API - this is something I struggled with in Rust port.

**Comment by lemire** [comment]
> It would be nice if unity repo had version tags just like the original CRoaring repo, what do you think?

Done.

> I'll take a look into iterator API - this is something I struggled with in Rust port.


I have not looked that the Rust code but I suspect that the C-based iterators might
