### ISSUE TITLE
Support for bitmaps > 2^32 

### ISSUE THREAD

**Issue by whitfin** [saulius/croaring-rs#30]
This is just a tracking issue for this repository for addition of support for 64 bit maps. It's highly related to https://github.com/RoaringBitmap/CRoaring/issues/1 seeing as we're binding the C layer (although if we could bind the C++ layer, that already appears to have an implementation?).

**Comment by saulius** [comment]
I have actually started implementing `RoaringTreeMap` for 64bit integer support. Just haven't finished it yet. Can't promise anything soon, but will try to prioritise this.

**Comment by whitfin** [comment]
Hi @saulius! Just wondering where you're at on this; perhaps I can contribute if you want to put what you have on a branch?

**Comment by saulius** [comment]
Hi @whitfin, I actually need this as well. Let me come up with something during the coming Eastern weekend.
