### ISSUE TITLE
Build error on WSL (Ubuntu 18.04)

### ISSUE THREAD

**Issue by mcdallas** [saulius/croaring-rs#34]
Hi, I am getting the following build error:

<details>

>    Compiling croaring-sys v0.3.5
> error: failed to run custom build command for `croaring-sys v0.3.5`
> process didn't exit successfully: `/home/mike/projects/test/target/debug/build/croaring-sys-cb06c0ed71cb48f6/build-script-build` (exit code: 101)
> --- stdout
> TARGET = Some("x86_64-unknown-linux-gnu")
> OPT_LEVEL = Some("0")
> TARGET = Some("x86_64-unknown-linux-gnu")
> HOST = Some("x86_64-unknown-linux-gnu")
> TARGET = Some("x86_64-unknown-linux-gnu")
> TARGET = Some("x86_64-unknown-linux-gnu")
> HOST = Some("x86_64-unknown-linux-gnu")
> CC_x86_64-unknown-linux-gnu = None
> CC_x86_64_unknown_linux_gnu = None
> HOST_CC = None
> CC = None
> HOST = Some("x86_64-unknown-linux-gnu")
> TARGET = Some("x86_64-unknown-linux-gnu")
> HOST = Some("x86_64-unknown-linux-gnu")
> CFLAGS_x86_64-unknown-linux-gnu = None
> CFLAGS_x86_64_unknown_linux_gnu = None
> HOST_CFLAGS = None
> CFLAGS = None
> DEBUG = Some("true")
> running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-std=c11" "-march=native" "-O3" "-Wall" "-Wextra" "-o" "/home/mike/projects/test/target/debug/build/croaring-sys-3d1f6d6d130d590f/out/CRoaring/roaring.o" "-c" "CRoaring/roaring.c"
> exit code: 0
> TARGET = Some("x86_64-unknown-linux-gnu")
> TARGET = Some("x86_64-unknown-linux-gnu")
> HOST = Some("x86_64-unknown-linux-gnu")
> AR_x86_64-unknown-linux-gnu = None
> AR_x86_64_unknown_linux_gnu = None
> HOST_AR = None
> AR = None
> TARGET = Some("x86_64-unknown-linux-gnu")
> TARGET = Some("x86_64-unknown-linux-gnu")
> running: "ar" "crs" "/home/mike/projects/test/target/debug/build/croaring-sys-3d1f6d6d130d590f/out/libroaring.a" "/home/mike/projects/test/target/debug/build/croaring-sys-3d1f6d6d130d590f/out/CRoaring/roaring.o"
> exit code: 0
> TARGET = Some("x86_64-unknown-linux-gnu")
> cargo:rustc-link-lib=static=roaring
> cargo:rustc-link-search=native=/home/mike/projects/test/target/debug/build/croaring-sys-3d1f6d6d130d590f/out
> 
> --- stderr
> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
> stack backtrace:
>    0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
>              at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
>    1: std::sys_common::backtrace::print
>              at libstd/sys_common/backtrace.rs:71
>              at libstd/sys_common/backtrace.rs:59
>    2: std::panicking::default_hook::{{closure}}
>              at libstd/panicking.rs:211
>    3: std::panicking::default_hook
>              at libstd/panicking.rs:227
>    4: std::panicking::rust_panic_with_hook
>              at libstd/panicking.rs:463
>    5: std::panicking::begin_panic_fmt
>              at libstd/panicking.rs:350
>    6: rust_begin_unwind
>              at libstd/panicking.rs:328
>    7: core::panicking::panic_fmt
>              at libcore/panicking.rs:71
>    8: core::panicking::panic
>              at libcore/panicking.rs:51
>    9: <core::option::Option<T>>::unwrap
>              at /checkout/src/libcore/macros.rs:20
>   10: clang_sys::load_manually::build::find
>              at /home/mike/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.23.0/src/../build.rs:244
>   11: clang_sys::load_manually::build::find_shared_library
>              at /home/mike/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.23.0/src/../build.rs:308
>   12: clang_sys::load_manually
>              at /home/mike/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.23.0/src/link.rs:120
>   13: clang_sys::load
>              at /home/mike/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-0.23.0/src/link.rs:142
>   14: core::ops::function::FnOnce::call_once
>              at /home/mike/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.37.4/src/lib.rs:1567
>              at /checkout/src/libcore/ops/function.rs:223
>   15: <lazy_static::lazy::Lazy<T>>::get::{{closure}}
>              at /home/mike/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.0.1/src/lazy.rs:24
>   16: std::sync::once::Once::call_once::{{closure}}
>              at /checkout/src/libstd/sync/once.rs:227
>   17: std::sync::once::Once::call_inner
>              at libstd/sync/once.rs:340
>   18: std::sync::once::Once::call_once
>              at /checkout/src/libstd/sync/once.rs:227
>   19: <bindgen::ensure_libclang_is_loaded::LIBCLANG as core::ops::deref::Deref>::deref
>              at /home/mike/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.0.1/src/lazy.rs:23
>              at /home/mike/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.37.4/<__lazy_static_internal macros>:13
>              at /home/mike/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.37.4/<__lazy_static_internal macros>:14
>   20: bindgen::ensure_libclang_is_loaded
>              at /home/mike/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.37.4/src/lib.rs:1574
>   21: bindgen::Bindings::generate
>              at /home/mike/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.37.4/src/lib.rs:1589
>   22: bindgen::Builder::generate
>              at /home/mike/.cargo/registry/src/github.com-1ecc6299db9ec823/bindgen-0.37.4/src/lib.rs:1139
>   23: build_script_build::main
>              at ./build.rs:15
>   24: std::rt::lang_start::{{closure}}
>              at /checkout/src/libstd/rt.rs:74
>   25: std::panicking::try::do_call
>              at libstd/rt.rs:59
>              at libstd/panicking.rs:310
>   26: __rust_maybe_catch_panic
>              at libpanic_unwind/lib.rs:105
>   27: std::rt::lang_start_internal
>              at libstd/panicking.rs:289
>              at libstd/panic.rs:374
>              at libstd/rt.rs:58
>   28: std::rt::lang_start
>              at /checkout/src/libstd/rt.rs:74
>   29: main
>   30: __libc_start_main
>   31: _start
> 

</details>

rust version 1.27

> clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
> Target: x86_64-pc-linux-gnu
> Thread model: posix
> InstalledDir: /usr/bin

Any idea what's wrong?

**Comment by saulius** [comment]
Hi @mcdallas,

Sorry for not getting back to you earlier. I just did a fresh install of Ubuntu 18.04 in a VM and was able to compile `croaring-rs` with by installing `clang` (`apt-get install clang`) and `libclang` (`apt-get install libclang1-6.0`). I see `: <bindgen::ensure_libclang_is_loaded::LIBCLANG as core::ops::deref::Deref>::deref` in your stacktrace so perhaps you are missing `libclang`?

**Comment by mcdallas** [comment]
Thanks for replying. Unfortunately that's not it as I have the latest `clang` and `libclang1-6.0` installed.

**Comment by mcdallas** [comment]
I can confirm that it works using a VM with Ubuntu18.04. The problem seems to be specific to WSL

**Comment by photis** [comment]
I'm running into the exact same error on my local hardware (Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz, 8 cores) with Ubuntu Linux 18.04.1 (Linux 4.15.0-33-generic on x86_64)

Rust version 1.28
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin


Log:
```
$ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading libc v0.2.43
 Downloading log v0.4.5
 Downloading env_logger v0.5.13
 Downloading cfg-if v0.1.5
 Downloading regex v1.0.4
 Downloading lazy_static v1.1.0
 Downloading bitflags v1.0.4
 Downloading termcolor v1.0.3
 Downloading memchr v2.0.2
 Downloading utf8-ranges v1.0.1
 Downloading thread_local v0.3.6
 Downloading aho-corasick v0.6.8
 Downloading cc v1.0.23
   Compiling version_check v0.1.4
   Compiling libc v0.2.43
   Compiling cc v1.0.23
   Compiling ucd-util v0.1.1
   Compiling regex v1.0.4
   Compiling glob v0.2.11
   Compiling quick-error v1.2.2
   Compiling unicode-xid v0.1.0
   Compiling unicode-width v0.1.5
   Compiling cfg-if v0.1.5
   Compiling utf8-ranges v1.0.1
   Compiling bitflags v1.0.4
   Compiling bindgen v0.37.4
   Compiling strsim v0.7.0
   Compiling ansi_term v0.11.0
   Compiling vec_map v0.8.1
   Compiling termcolor v1.0.3
   Compiling peeking_take_while v0.1.2
   Compiling gcc v0.3.54
   Compiling humantime v1.1.1
   Compiling proc-macro2 v0.3.5
   Compiling log v0.4.5
   Compiling textwrap v0.10.0
   Compiling regex-syntax v0.6.2
   Compiling lazy_static v1.1.0
   Compiling clang-sys v0.23.0
   Compiling memchr v2.0.2
   Compiling memchr v1.0.2
   Compiling atty v0.2.11
   Compiling which v1.0.5
   Compiling libloading v0.5.0
   Compiling aho-corasick v0.6.8
   Compiling nom v3.2.1
   Compiling clap v2.32.0
   Compiling quote v0.5.2
   Compiling thread_local v0.3.6
   Compiling cexpr v0.2.3
   Compiling env_logger v0.5.13
   Compiling croaring-sys v0.3.6 (file:///home/photis/Projects/croaring-rs/croaring-sys)
error: failed to run custom build command for `croaring-sys v0.3.6 (file:///home/photis/Projects/croaring-rs/croaring-sys)`
process didn't exit successfully: `/home/photis/Projects/croaring-rs/target/debug/build/croaring-sys-f36e0c4a7d2ab2f9/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-m64" "-std=c11" "-march=native" "-O3" "-Wall" "-Wextra" "-o" "/home/photis/Projects/croaring-rs/target/debug/build/croaring-sys-a92da1a15ddb0f83/out/CRoaring/roaring.o" "-c" "CRoaring/roaring.c"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
AR_x86_64-unknown-linux-gnu = None
AR_x86_64_unknown_linux_gnu = None
HOST_AR = None
AR = None
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
running: "ar" "crs" "/home/photis/Projects/croaring-rs/target/debug/build/croaring-sys-a92da1a15ddb0f83/out/libroaring.a" "/home/photis/Projects/croaring-rs/target/debug/build/croaring-sys-a92da1a15ddb0f83/out/CRoaring/roaring.o"
exit code: 0
TARGET = Some("x86_64-unknown-linux-gnu")
cargo:rustc-link-lib=static=roaring
cargo:rustc-link-search=native=/home/photis/Projects/croaring-rs/target/debug/build/croaring-sys-a92da1a15ddb0f83/out

--- stderr
/usr/include/clang/6.0.0/include/xmmintrin.h:2968:44: error: token is not a valid binary operator in a preprocessor subexpression
/usr/include/clang/6.0.0/include/emmintrin.h:1414:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size
/usr/include/clang/6.0.0/include/emmintrin.h:2280:66: error: cannot convert between vector values of different size ('__v16hu' (vector of 16 'unsigned short' values) and 'int')
/usr/include/clang/6.0.0/include/emmintrin.h:2304:64: error: cannot convert between vector values of different size ('__v8su' (vector of 8 'unsigned int' values) and 'int')
/usr/include/clang/6.0.0/include/avx2intrin.h:151:66: error: cannot convert between vector values of different size ('__v32hu' (vector of 32 'unsigned short' values) and 'int')
/usr/include/clang/6.0.0/include/avx2intrin.h:161:66: error: cannot convert between vector values of different size ('__v16su' (vector of 16 'unsigned int' values) and 'int')
/usr/include/clang/6.0.0/include/fmaintrin.h:49:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size
/usr/include/clang/6.0.0/include/fmaintrin.h:55:10: error: invalid conversion between vector type '__m128d' (vector of 2 'double' values) and integer type 'int' of different size
/usr/include/clang/6.0.0/include/fmaintrin.h:73:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size
/usr/include/clang/6.0.0/include/fmaintrin.h:79:10: error: invalid conversion between vector type '__m128d' (vector of 2 'double' values) and integer type 'int' of different size
/usr/include/clang/6.0.0/include/fmaintrin.h:97:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size
/usr/include/clang/6.0.0/include/fmaintrin.h:103:10: error: invalid conversion between vector type '__m128d' (vector of 2 'double' values) and integer type 'int' of different size
/usr/include/clang/6.0.0/include/fmaintrin.h:121:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size
/usr/include/clang/6.0.0/include/fmaintrin.h:127:10: error: invalid conversion between vector type '__m128d' (vector of 2 'double' values) and integer type 'int' of different size
/usr/include/clang/6.0.0/include/avx512fintrin.h:223:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
/usr/include/clang/6.0.0/include/avx512fintrin.h:231:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
/usr/include/clang/6.0.0/include/avx512fintrin.h:247:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
/usr/include/clang/6.0.0/include/avx512fintrin.h:256:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
/usr/include/clang/6.0.0/include/avx512fintrin.h:322:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size
fatal error: too many errors emitted, stopping now [-ferror-limit=]
/usr/include/clang/6.0.0/include/xmmintrin.h:2968:44: error: token is not a valid binary operator in a preprocessor subexpression, err: true
/usr/include/clang/6.0.0/include/emmintrin.h:1414:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size, err: true
/usr/include/clang/6.0.0/include/emmintrin.h:2280:66: error: cannot convert between vector values of different size ('__v16hu' (vector of 16 'unsigned short' values) and 'int'), err: true
/usr/include/clang/6.0.0/include/emmintrin.h:2304:64: error: cannot convert between vector values of different size ('__v8su' (vector of 8 'unsigned int' values) and 'int'), err: true
/usr/include/clang/6.0.0/include/avx2intrin.h:151:66: error: cannot convert between vector values of different size ('__v32hu' (vector of 32 'unsigned short' values) and 'int'), err: true
/usr/include/clang/6.0.0/include/avx2intrin.h:161:66: error: cannot convert between vector values of different size ('__v16su' (vector of 16 'unsigned int' values) and 'int'), err: true
/usr/include/clang/6.0.0/include/fmaintrin.h:49:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size, err: true
/usr/include/clang/6.0.0/include/fmaintrin.h:55:10: error: invalid conversion between vector type '__m128d' (vector of 2 'double' values) and integer type 'int' of different size, err: true
/usr/include/clang/6.0.0/include/fmaintrin.h:73:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size, err: true
/usr/include/clang/6.0.0/include/fmaintrin.h:79:10: error: invalid conversion between vector type '__m128d' (vector of 2 'double' values) and integer type 'int' of different size, err: true
/usr/include/clang/6.0.0/include/fmaintrin.h:97:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size, err: true
/usr/include/clang/6.0.0/include/fmaintrin.h:103:10: error: invalid conversion between vector type '__m128d' (vector of 2 'double' values) and integer type 'int' of different size, err: true
/usr/include/clang/6.0.0/include/fmaintrin.h:121:10: error: invalid conversion between vector type '__m128' (vector of 4 'float' values) and integer type 'int' of different size, err: true
/usr/include/clang/6.0.0/include/fmaintrin.h:127:10: error: invalid conversion between vector type '__m128d' (vector of 2 'double' values) and integer type 'int' of different size, err: true
/usr/include/clang/6.0.0/include/avx512fintrin.h:223:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
/usr/include/clang/6.0.0/include/avx512fintrin.h:231:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
/usr/include/clang/6.0.0/include/avx512fintrin.h:247:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
/usr/include/clang/6.0.0/include/avx512fintrin.h:256:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
/usr/include/clang/6.0.0/include/avx512fintrin.h:322:10: error: invalid conversion between vector type '__m512i' (vector of 8 'long long' values) and integer type 'int' of different size, err: true
fatal error: too many errors emitted, stopping now [-ferror-limit=], err: true
thread 'main' panicked at 'Unable to generate bindings: ()', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Sorry for the long code block, couldn't figure out how @mcdallas did that neat trick with the collapsing triangle. Teach me, please.

**Comment by Nemo157** [comment]
@photis it's done by putting some raw html in your comment, something like:

```html
<details><summary>text to show next to triangle</summary>

Whatever you want to show inside collapsed block

</details>
```

(the blank lines are needed to have the inner part rendered as markdown) e.g.:

<details><summary>text to show next to triangle</summary>

Whatever you want to show inside collapsed block

</details>

**Comment by photis** [comment]
@Nemo157 Cool! Thank you! 🤗

**Comment by photis** [comment]
An update to my own comment: after I removed the `clang` package as shown below, and `cargo build` again, I got no more build errors. Beats me what was going on (what is the "exp5" in the removal line???), but leaving this here as a suggestion for future problem owners.
```
$ sudo apt-get purge --auto-remove clang
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED
  clang*
0 to upgrade, 0 to newly install, 1 to remove and 0 not to upgrade.
After this operation, 22.5 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 245541 files and directories currently installed.)
Removing clang (1:6.0-41~exp5~ubuntu1) ...
Processing triggers for man-db (2.8.3-2) ...
$
```

**Comment by saulius** [comment]
Can you guys try version 0.3.8 of `croaring-rs`? [As reported by Travis](https://travis-ci.org/saulius/croaring-rs/builds/479556234) it should build under various clang/gcc flavours.

**Comment by saulius** [comment]
Closing this, let me know if this still an issue.
