### ISSUE TITLE
Treemap::andnot_inplace clears the treemap when comparing to empty treemap

### ISSUE THREAD

**Issue by SWvheerden** [saulius/croaring-rs#49]
I dont know of this is intended behavior or a bug, but if you have two treemaps with one empty, it will clear the other one as well.   Running the following code reproduces the error:

    let mut treemap1 = Treemap::create();

    treemap1.add(15);

    let mut treemap2 = Treemap::create();

    treemap1.andnot_inplace(&treemap2);

    assert_eq!(treemap1.cardinality(), 1);
    assert!(treemap1.contains(15));

The test will fail, and if read the documentation right it should not.

**Comment by saulius** [comment]
This is definitely a bug, will check it out.

**Comment by SWvheerden** [comment]
Should be an easy fix, in my code I just bypass the `andnot_inplace` if the second tree is empty
