### ISSUE TITLE
Expose roaring_read_uint32_iterator safely

### ISSUE THREAD

**Issue by farnoy** [saulius/croaring-rs#51]
Hey, could we get this method wrapped safely on `BitmapIterator`: https://docs.rs/croaring-sys/0.4.0/croaring_sys/fn.roaring_read_uint32_iterator.html ?

**Comment by saulius** [comment]
Hi @farnoy, would something like in above merge request work?

**Comment by farnoy** [comment]
@saulius I posted a quick review there, yes that is perfect to address this issue.
