### ISSUE TITLE
Serialization always starts with same bytes

### ISSUE THREAD

**Issue by AngelOnFira** [saulius/croaring-rs#54]
I don't have enough time to dive into the serialization code, however, it appears that the first bytes of every serialized bitmap are `0x3b 30 00 00 01 00 00`.

Are there any cases in which these are different? Can these be removed and added back on my end?

**Comment by Nemo157** [comment]
The spec is at https://github.com/RoaringBitmap/RoaringFormatSpec, first two bytes identify the data type so could be trimmed if you always serialize to the same format. The rest of the bytes depend on the values stored, it must just happen that all the bitmaps you've looked at have used a single container encoded in run format.
