### ISSUE TITLE
Consider supporting a later version of the bindgen

### ISSUE THREAD

**Issue by frostRed** [saulius/croaring-rs#55]
In croaring-sys Cargo.toml, it require bindgen's version cannot exceed 0.49.

```
bindgen = ">= 0.37, <= 0.49"
```

If a project depends on other C wrappers, a compilation error will occur.

```
error:  multiple packages link to native library `clang`, but a native library can be linked only once
```

**Comment by omac777** [comment]
Please commit the following and it should build with the latest rust nightly.
Essentially using the latest bindgen within the Cargo.toml with the latest nightly and you should be good to go.

Please remember when you build, you need to build the croaring-sys subdirectory first
Also add two rust-toolchain files pointing to "nightly-2019-12-06" to both croaring-rs and croaring-sys.

```
diff --git a/Cargo.toml b/Cargo.toml
index 314fd9e..047e86f 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -15,5 +15,5 @@ roaring = "0.5.2"
 
 [dependencies]
 libc = "0.2.42"
-croaring-sys = { path = "croaring-sys", version = "0.4.1" }
+croaring-sys = { path = "croaring-sys" }
 byteorder = "1"
diff --git a/croaring-sys/Cargo.toml b/croaring-sys/Cargo.toml
index 695b431..bdd2b5a 100644
--- a/croaring-sys/Cargo.toml
+++ b/croaring-sys/Cargo.toml
@@ -14,5 +14,4 @@ libc = "0.2.42"
 
 [build-dependencies]
 cc = "1.0"
-bindgen = ">= 0.37, <= 0.49"
-
+bindgen = "0.52.0"
```

**Comment by omac777** [comment]
oh yes, please ensure you did install clang, llvm, lld and that should suffice.
