### ISSUE TITLE
Make -march=native entirely optional to the build in croaring-sys

### ISSUE THREAD

**Issue by StriderDM** [saulius/croaring-rs#61]
The `-march=native` flag severely limits compatibility with a variety of hardware other than the cpu it was built on and direct descendants of it. So it can be pretty destructive if you are trying to release binaries and not have people compile it them themselves. To create portable binaries this flag must not be present.

The current problem is this flag is included in the build if the compiler supports it, which means that in a great majority of cases this flag will be passed where in many cases this is not the desired result that the programmer is trying to achieve.

Admittedly I have run into this footgun before.

This needs to be removed:
https://github.com/saulius/croaring-rs/blob/cf74f5749fd77d485e74002cd20ca27be23b53ad/croaring-sys/build.rs#L10-L11

I'd suggest rather assigning this to an environment variable where it can be checked by the `build.rs` script and used if needed. You could also probably indicate that this flag be put into the CFLAGS and CXXFLAGS variables which would be picked up by the C compiler at build time.

**Comment by saulius** [comment]
Thanks, this makes sense. I put https://github.com/saulius/croaring-rs/pull/62 to solve this.
