### ISSUE TITLE
Iterating over all values in bitmap seems slow

### ISSUE THREAD

**Issue by e-dard** [saulius/croaring-rs#63]
Hi,

I'm using `croaring` to maintain some indexes for me. At some point I need to iterate through my bitmap of indexes, lookup some values at those indexes in another slice, and sum the values. I have found through some performance testing that for my usecase this:

```rust
let mut res =  0;
let vec = bm.to_vec();
for v in vec {
    res += self.values[v as usize];
}
```

is almost twice as fast as this:

```rust
let mut res =  0;
for v in row_ids.iter() {
     res += self.values[v];
}
```

There are about `60,000` possible indexes, and typically the bitmaps contain hundreds to upto maybe 20,000 values. What I find interesting is that `to_vec()` plus the Rust loop involves the same amount of iteration,  so I think something is perhaps off with exposed iterator implementation on `BitMap`?

**Comment by saulius** [comment]
Hi @e-dard,

I haven't run any benchmarks, but I still think we can expect this behaviour. The reason being that by materializing `Bitmap` as a vector you allocate a chunk of linear memory for all Bitmap's values. It's hard or even impossible to beat iteration through linear  memory which may as well even fit in one of your CPU caches. The obvious trade off here is of course that you have to allocate such amount of memory upfront. However, with Roaring Bitmap's iterator we just allocate a small iterator instance and keep a single bitmap index value in memory throughout iteration. So this requires constant, small amount of memory. Moreover, doing iteration requires at least a few additional function calls like `iterator.current_value` and `iterator.has_value` which of course have an impact on iteration performance as well. So you have a memory/performance trade off here. Hope this helps!

**Comment by e-dard** [comment]
That explanation makes a lot of sense to me. One suggestion I have is to provide an API that would allow one to provide a buffer to write the contents of the bitmap into.

So, as well as `to_vec()` there would also be `into_vec(&mut buf: Vec<u32>)` or something similar.

Do you think that would be a good change?

**Comment by saulius** [comment]
That would definitely be a good change. `croaring` has `roaring_read_uint32_iterator` function for exactly this use case and [it's definitely faster than unbounded iteration](https://github.com/RoaringBitmap/CRoaring/blob/b6cacb9a6fde5a34cfc7d2783d5af0627b915c49/benchmarks/iteration_benchmark.c#L18-L34):

```
./iteration_benchmark ../../benchmarks/realdata/census1881/*
Data:
  cardinality: 988653
Cycles/element:
  roaring_advance_uint32_iterator(): 14.492519 13.798000 13.844965 13.889676 13.953517
  roaring_read_uint32_iterator(bufsize=1): 19.190871 19.074035 20.081280 18.888611 19.243656
  roaring_read_uint32_iterator(bufsize=4): 8.188877 8.147134 8.211180 7.934367 8.095384
  roaring_read_uint32_iterator(bufsize=16): 5.059551 4.899865 5.011902 4.999459 5.105984
  roaring_read_uint32_iterator(bufsize=128): 3.762317 3.737760 3.823841 3.847504 3.778094
  roaring_read_uint32_iterator(bufsize=1024): 3.629963 3.755138 3.880000 3.829131 3.664821
```

**Comment by e-dard** [comment]
@saulius I'm going to take some vacation shortly but when I get back I'll have a go at that change.

**Comment by saulius** [comment]
Please try https://docs.rs/croaring/latest/croaring/bitmap/struct.BitmapIterator.html#method.next_many in `croaring` `0.5.2`.
