### ISSUE TITLE
Bundle pre-bindgen'd bindings for -sys package

### ISSUE THREAD

**Issue by Dr-Emann** [saulius/croaring-rs#89]
Since we're bundling the version of CRoaring, we should be able to create the bindings offline, and update them manually when we bump the bundled version. This would remove bindgen from the build dependencies, which should have a pretty big build-time speed up, and avoid having dependencies on libclang (to fix #76).

**Comment by saulius** [comment]
Great idea, I agree! Do you know any Rust libs that do this already?

**Comment by saulius** [comment]
Fixed in #95.
