### ISSUE TITLE
Updating CRoaring to latest version (0.2.4)

### ISSUE THREAD

**Issue by lemire** [saulius/croaring-rs#9]
The latest version exposes the CRoaring version:

https://github.com/RoaringBitmap/CRoaring/blob/master/include/roaring/roaring_version.h

This could be handy.

There is also a function to add a bunch of integers quickly...

```
 void roaring_bitmap_add_many(roaring_bitmap_t * r, size_t n_args, const uint32_t *vals);
```

**Comment by saulius** [comment]
It seems the performance increased as well:

https://travis-ci.org/saulius/croaring-rs/jobs/158952533#L515 vs https://travis-ci.org/saulius/croaring-rs/jobs/158963043#L516

Nice work!
